odiseo_sylius_blog_plugin_api_admin_article_category:
    resource: |
        identifier: code
        alias: odiseo_blog.article_category
        section: admin_api
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api
