odiseo_sylius_blog_plugin_api_admin_article_comment:
    resource: |
        identifier: id
        alias: odiseo_blog.article_comment
        section: admin_api
        serialization_version: $version
        criteria:
            id: $id
    type: sylius.resource_api
